version: "3"
services:
  clientelle:
    build:
      context: .
      dockerfile: dockerfile
    ports: 
      - 5000:5000
    volumes:
      - ./src:/usr/app/src  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"